/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { LotterexContract } from "./Lotterex";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Lotterex"): LotterexContract;
    }
  }
}

export { LotterexContract, LotterexInstance } from "./Lotterex";
